# Generated by Django 5.0.2 on 2025-01-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_registration_date_eventregistration_registered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='registered_at',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
