# Generated by Django 5.0.2 on 2025-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_registered_at_eventregistration_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=3, upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
