# Generated by Django 5.0.2 on 2025-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_image_event_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='urls',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='event',
            name='doc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
