# Generated by Django 5.0.2 on 2024-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='set_password',
            field=models.CharField(default=66785, max_length=50),
            preserve_default=False,
        ),
    ]
