# Generated by Django 5.0.2 on 2024-11-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
