# Generated by Django 5.0.2 on 2025-01-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='time',
        ),
    ]
